/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labirinto;

import java.awt.Event;

/**
 *
 * @author Gabriel
 */
public class Direcao extends javax.swing.JFrame {
    String[] retorno;
    String evento, score;
    int dif ,vidaAtual=3, pontos,pontuacao=0,movimentos=0;

    @Override
    public void deliverEvent(Event event) {
        super.deliverEvent(event); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form Direcao
     * @param d
     */
    public Direcao(int d) {
        this.dif = d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        highScore = new javax.swing.JLabel();
        logsEvento = new javax.swing.JLabel();
        norte = new javax.swing.JButton();
        sul = new javax.swing.JButton();
        leste = new javax.swing.JButton();
        oeste = new javax.swing.JButton();
        vida = new javax.swing.JLabel();
        rdv = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        highScore.setFont(new java.awt.Font("Vineta BT", 0, 36)); // NOI18N
        highScore.setText("100");
        getContentPane().add(highScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 40));

        logsEvento.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        logsEvento.setForeground(new java.awt.Color(255, 255, 0));
        logsEvento.setText("A dona aranha subiu pela parede. Veio a chuva forte e a derrubou.");
        getContentPane().add(logsEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 470, 80));

        norte.setText("N");
        norte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norteActionPerformed(evt);
            }
        });
        getContentPane().add(norte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 50, 20));

        sul.setText("S");
        sul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sulActionPerformed(evt);
            }
        });
        getContentPane().add(sul, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 50, 20));

        leste.setText("L");
        leste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lesteActionPerformed(evt);
            }
        });
        getContentPane().add(leste, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        oeste.setText("O");
        oeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oesteActionPerformed(evt);
            }
        });
        getContentPane().add(oeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        vida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/3.jpg"))); // NOI18N
        getContentPane().add(vida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        rdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/rdv.jpg"))); // NOI18N
        getContentPane().add(rdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/labirinto.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void norteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norteActionPerformed
        if (pontuacao>=100){
            new Vitoria(movimentos).setVisible(true);
            dispose();
        }
        movimentos = movimentos +1;
        Norte n= new Norte();
        retorno = n.Norte(dif);
        evento = retorno[0];
        vidaAtual = vidaAtual - Integer.parseInt(retorno[1]);
        pontos = Integer.parseInt(retorno[2]);
        pontuacao = pontuacao + pontos;
        logsEvento.setText(evento);
        highScore.setText(Integer.toString(pontuacao));
        vida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/"+vidaAtual+".jpg")));
        if (vidaAtual ==0){
            new Derrota().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_norteActionPerformed

    private void oesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oesteActionPerformed
        if (pontuacao>=100){
            new Vitoria(movimentos).setVisible(true);
            dispose();
        }
        movimentos = movimentos +1;
        Oeste o= new Oeste();
        retorno = o.Oeste(dif);
        evento = retorno[0];
        vidaAtual = vidaAtual - Integer.parseInt(retorno[1]);
        pontos = Integer.parseInt(retorno[2]);
        pontuacao = pontos +pontuacao;
        logsEvento.setText(evento);
        highScore.setText(Integer.toString(pontuacao));
        vida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/"+vidaAtual+".jpg")));
        if (vidaAtual ==0){
            new Derrota().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_oesteActionPerformed

    private void lesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lesteActionPerformed
        if (pontuacao>=100){
            new Vitoria(movimentos).setVisible(true);
            dispose();
        }
        movimentos = movimentos +1;
        Leste l= new Leste();
        retorno = l.Leste(dif);
        evento = retorno[0];
        vidaAtual = vidaAtual - Integer.parseInt(retorno[1]);
        pontos = Integer.parseInt(retorno[2]);
        pontuacao = pontos +pontuacao;
        logsEvento.setText(evento);
        highScore.setText(Integer.toString(pontuacao));
        vida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/"+vidaAtual+".jpg")));
        if (vidaAtual ==0){
            new Derrota().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lesteActionPerformed

    private void sulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sulActionPerformed
        if (pontuacao>=100){
            new Vitoria(movimentos).setVisible(true);
            dispose();
        }
        movimentos = movimentos +1;
        Sul s= new Sul();
        retorno = s.Sul(dif);
        evento = retorno[0];
        vidaAtual = vidaAtual - Integer.parseInt(retorno[1]);
        pontos = Integer.parseInt(retorno[2]);
        pontuacao = pontos +pontuacao;
        logsEvento.setText(evento);
        highScore.setText(Integer.toString(pontuacao));
        vida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/"+vidaAtual+".jpg")));
        if (vidaAtual ==0){
            new Derrota().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_sulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Direcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Direcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Direcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Direcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel highScore;
    private javax.swing.JButton leste;
    private javax.swing.JLabel logsEvento;
    private javax.swing.JButton norte;
    private javax.swing.JButton oeste;
    private javax.swing.JLabel rdv;
    private javax.swing.JButton sul;
    private javax.swing.JLabel vida;
    // End of variables declaration//GEN-END:variables
}
