/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labirinto;

/**
 *
 * @author gabriel.paiva
 */
public class oBau extends javax.swing.JFrame {
    String evento="Você continua seu caminho.",stats="0",score="0";
    String[] retorno = new String []{evento,stats,score};
    
    /**
     * Creates new form oBau 
     */
    public oBau() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        abrir = new javax.swing.JButton();
        ignorar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 51));
        text.setText("Você encontrou um Báu!");
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 360, 50));

        abrir.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        getContentPane().add(abrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 90, -1));

        ignorar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        ignorar.setText("Ignorar");
        ignorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignorarActionPerformed(evt);
            }
        });
        getContentPane().add(ignorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/bau.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        retorno = new Bau().Bau();
        
        dispose();
     }//GEN-LAST:event_abrirActionPerformed

    private void ignorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignorarActionPerformed
        dispose();
    }//GEN-LAST:event_ignorarActionPerformed

    public String[] getRetorno() {
        return retorno;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oBau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oBau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oBau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oBau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton ignorar;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
