/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labirinto;

/**
 *
 * @author Gabriel
 */
public class Vitoria extends javax.swing.JFrame {

    /**
     * Creates new form Vitoria
     * @param movimentos
     */
    public Vitoria(int movimentos) {
        initComponents();
        numMovimentos.setText("Número de movimentos: "+movimentos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agradecimento = new javax.swing.JLabel();
        numMovimentos = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        continuar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agradecimento.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        agradecimento.setForeground(new java.awt.Color(0, 255, 255));
        agradecimento.setText("Você encontrou a saída!");
        getContentPane().add(agradecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 300, 40));

        numMovimentos.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        numMovimentos.setForeground(new java.awt.Color(0, 255, 255));
        numMovimentos.setText("Número de movimentos: ");
        getContentPane().add(numMovimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 390, 30));

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 90, -1));

        continuar.setText("Novo Jogo");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        getContentPane().add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 90, -1));

        fundo.setBackground(new java.awt.Color(0, 0, 0));
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labirinto/images/gameOver.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_continuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vitoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agradecimento;
    private javax.swing.JButton continuar;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel numMovimentos;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
